title: <p align="center"> Arya Pathak </p>
logo: /assets/img/logo.jpg
description:
  <p align="center">
  Pune, India
  <br> arya.pathak@outlook.in
  <br> <a href="https://drive.google.com/drive/folders/16tRJ-f4vwvIpvN5G2s_3m-qIJDJ09DgS">Resume</a> |
  <a href="https://www.linkedin.com/in/arya-pathak-a53a58256/">LinkedIn</a> |
  <a href="https://github.com/arya2004">GitHub</a>
  <br> <a href="https://stackoverflow.com/users/14389995/arya2004">Stack Overflow</a> | 
  <a href="https://arya2004.hashnode.dev/">Hashnode</a>
  <br> <a href="https://x.com/_arya2004">X/Twitter</a> |
  </p>
  
  <p align="justify">
    I am a <strong>Backend Developer</strong> and <strong>Cat Connoisseur</strong>. Currently, I am pursuing a degree in Computer Engineering at Vishwakarma Institute of Technology, Pune. My skill set includes programming languages such as C#, Java, Go, and Python, along with cloud technologies like Kubernetes and Azure. I have been recognized in hackathons and actively contribute to open-source projects. I am deeply passionate about technology and committed to continuous learning.<br><br>
  </p>


show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 