title: <p align="center"> Arya Pathak </p>
logo: /assets/img/logo.jpg
description:
  <p align="center">
      Pune, India
      <br />
      arya.pathak@outlook.in <br />
      <a href="https://drive.google.com/drive/folders/16tRJ-f4vwvIpvN5G2s_3m-qIJDJ09DgS">Resume</a>
  </p>

  <p align="justify">
      I am a <strong> Software Developer</strong> specializing in backend systems and cloud-native applications. I am currently pursuing a B.Tech in Computer Engineering at Vishwakarma Institute of Technology, Pune. Proficient in languages C#, Go, and Python, and technologies ASP.NET Core, Angular, Kubernetes, and Azure, I have developed scalable solutions and contributed to open-source projects.<br /><br />
  </p>


show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 