title: <p align="center"> Arya Pathak </p>
logo: /assets/img/logo.jpg
description:
  <p align="center">
  Pune, India
  <br> arya.pathak@outlook.in
  <br> <a href="https://drive.google.com/drive/folders/16tRJ-f4vwvIpvN5G2s_3m-qIJDJ09DgS">Resume</a> |
  <a href="https://www.linkedin.com/in/arya-pathak-a53a58256/">LinkedIn</a> |
  <a href="https://github.com/arya2004">GitHub</a>
  <br> <a href="https://stackoverflow.com/users/14389995/arya2004">Stack Overflow</a> | 
  <a href="https://arya2004.hashnode.dev/">Hashnode</a>
  <br> <a href="https://x.com/_arya2004">X/Twitter</a> |
  </p>
  
  <p align="justify">
  I am a <b>Backend Developer</b> who likes Cats. 
  <br>
  I am a Computer Engineering student at Vishwakarma Institute of Technology, Pune
  <bam
  <br>
  My skills include C#, Java, Go, Python, and cloud technologies like Kubernetes and Azure. Recognized in hackathons and active in open-source contributions, I'm passionate about technology and continuous learning.
  <br><br>
  </p>


show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
