title: <p align="center"> Arya Pathak </p>
logo: /assets/img/logo.png
description: |
  <p align="center">
      Pune, India
      <br />
      arya.m.pathak@gmail.com
      <br />
      <a href="https://drive.google.com/drive/folders/16tRJ-f4vwvIpvN5G2s_3m-qIJDJ09DgS">Resume</a>
  </p>

  <p align="justify">
      Backend and cloud engineer skilled in Go, Python, and C#. Experienced with Kubernetes, Docker, Azure, AWS, and GCP. Built scalable APIs, monitoring tools, and automation systems using PostgreSQL, MongoDB, and CI/CD pipelines.
  </p>



show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 